kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: management
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30443
    hostPort: 30443
    protocol: TCP
  extraMounts:
  - hostPath: /home/pedro/repos/kubernetes-intro/cluster-management/data/argocd
    containerPath: /var/argocd-data
    readOnly: false
